fix GCC 12 -Werror=mismatched-new-delete errors
error: 'void operator delete(void*, std::size_t)' called on pointer
returned from a mismatched allocation function
[-Werror=mismatched-new-delete]

Use `delete[]` instead of `delete` when deleting an array.